project:
  type: book
  output-dir: reports/harmonisation_summary_report


book:
  downloads: [docx]
  title: "Harmonisation Summary Report Template"
  navbar:
    search: true
  sidebar:
    collapse-level: 1

  chapters:
    - index.qmd
    - codes/harmonisation_summary/list_of_figures_tables.qmd
    - part: Cohort
      chapters:
        - codes/harmonisation_summary/cohort_introduction.qmd
    - part: Demographic and Clinical Variables
      chapters:
        - codes/harmonisation_summary/clinical_harmonisation.qmd
    - codes/harmonisation_summary/references.qmd

crossref:
  chapters: false
  # fig-title: Figure S     # (default is "Figure")
  # tbl-title: Table S     # (default is "Table")
  # fig-prefix: Figure S   # (default is "Figure")
  # tbl-prefix: Table S    # (default is "Table")
  # ref-hyperlink: true # (default is true)
  # title-delim: ":"   # (default is ":")
  custom:
    - key: suppfig
      kind: float
      latex-env: suppfig
      reference-prefix: Figure S
      space-before-numbering: false
      latex-list-of-description: Supplementary Figure
      caption-location: top
    - key: supptbl
      kind: float
      latex-env: supptbl
      reference-prefix: Table S
      space-before-numbering: false
      latex-list-of-description: Supplementary Table
      caption-location: top


bibliography: references.bib
csl: csl_file.csl

format:
  html:
    toc: true
    toc-depth: 5
    toc-location: right
    toc-expand: true
    number-sections: true
    number-depth: 5
    smooth-scroll: true
    theme:
      light:
        - flatly
      dark:
        - solar
  docx:
    toc: true
    number-sections: true
    number-depth: 6
    reference-doc: custom-reference.docx
    highlight-style: github



