project:
  type: book
  output-dir: reports/all

book:
  downloads: [pdf, docx]
  title: "Harmonisation Template For All Cohorts"
  author: "My Name"
  navbar:
    search: true
  sidebar:
    collapse-level: 1

  chapters:
    - index.qmd
    - part: Cohort A Cleaning
      chapters:
        - codes/Cohort_A/00_R_Package_And_Environment.qmd
        - codes/Cohort_A/01_Read_Cohort_A_Data.qmd
        - codes/Cohort_A/02_Extract_Demographic.qmd
        - codes/Cohort_A/03_Export_To_Excel.qmd
    - part: Cohort B Cleaning
      chapters:
        - codes/Cohort_B/00_R_Package_And_Environment.qmd
        - codes/Cohort_B/01_Read_Cohort_B_Data.qmd
        - codes/Cohort_B/02_Extract_Demographic.qmd
        - codes/Cohort_B/03_Export_To_Excel.qmd

crossref:
  chapters: false
  fig-title: Figure     # (default is "Figure")
  tbl-title: Table      # (default is "Table")
  fig-prefix: Figure    # (default is "Figure")
  tbl-prefix: Table     # (default is "Table")
  ref-hyperlink: true   # (default is true)
  title-delim: ":"      # (default is ":")

bibliography: references.bib
csl: csl_file.csl

format:
  html:
    toc: true
    toc-depth: 5
    toc-location: right
    toc-expand: true
    number-sections: true
    number-depth: 5
    smooth-scroll: true
    theme:
      light:
        - flatly
      dark:
        - solar
