project:
  type: book
  output-dir: reports/harmonisation_summary_report


book:
  title: "Harmonisation Summary Report Template"
  navbar:
    search: true
  sidebar:
    collapse-level: 1

  chapters:
    - index.qmd
    - codes/harmonisation_summary/list_of_figures_tables.qmd
    - codes/harmonisation_summary/supplementary.qmd
    - codes/harmonisation_summary/references.qmd

crossref:
  chapters: false
  # fig-title: Figure S     # (default is "Figure")
  # tbl-title: Table S     # (default is "Table")
  # fig-prefix: Figure S   # (default is "Figure")
  # tbl-prefix: Table S    # (default is "Table")
  # ref-hyperlink: true # (default is true)
  # title-delim: ":"   # (default is ":")
  custom:
    - key: suppfig
      kind: float
      latex-env: suppfig
      reference-prefix: Figure S
      space-before-numbering: false
      latex-list-of-description: Supplementary Figure
      caption-location: top
    - key: supptbl
      kind: float
      latex-env: supptbl
      reference-prefix: Table S
      space-before-numbering: false
      latex-list-of-description: Supplementary Table
      caption-location: top


bibliography: references.bib
csl: csl_file.csl

format:
  # html:
  #   toc: true
  #   toc-depth: 5
  #   toc-location: right
  #   toc-expand: true
  #   number-sections: true
  #   number-depth: 5
  #   smooth-scroll: true
  #   theme:
  #     light:
  #       - flatly
  #     dark:
  #       - solar
  docx:
    toc: true
    number-sections: true
    number-depth: 6
    reference-doc: custom-reference.docx
    highlight-style: github
  # pdf:
  #   pdf-engine: xelatex
  #   # prefer-html: true  # does not work with html widgets like reactable
  #   documentclass: scrreprt
  #   papersize: a4
  #   toc-depth: 5
  #   number-sections: true
  #   number-depth: 5
  #   keep-tex: false
  #   keep-md: false
  #   include-in-header:
  #     text: |
  #       \usepackage{fvextra}
  #       \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
  #       \DefineVerbatimEnvironment{OutputCode}{Verbatim}{breaklines,commandchars=\\\{\}}
  #   include-before-body:
  #     text: |
  #      \begin{flushleft}
  #      \begin{sloppypar}
  #       \RecustomVerbatimEnvironment{verbatim}{Verbatim}{
  #         showspaces = false,
  #         showtabs = false,
  #         breaksymbolleft={}, % Need pacakge fvextra
  #         breaklines
  #         % Note: setting commandchars=\\\{\} here will cause an error
  #       }
  #   include-after-body:
  #     text: |
  #       \end{sloppypar}
  #       \end{flushleft}



