project:
  type: book
  output-dir: reports/Cohort_B

book:
  downloads: [pdf, docx]
  title: "Harmonisation Template for Cohort B"
  author: "My Name"
  navbar:
    search: true
  sidebar:
    collapse-level: 1

  chapters:
    - index.qmd
    - part: Cohort B Cleaning
      chapters:
        - codes/Cohort_B/00_R_Package_And_Environment.qmd
        - codes/Cohort_B/01_Read_Cohort_B_Data.qmd
        - codes/Cohort_B/02_Extract_Demographic.qmd
        - codes/Cohort_B/03_Export_To_Excel.qmd

crossref:
  chapters: false
  fig-title: Figure     # (default is "Figure")
  tbl-title: Table      # (default is "Table")
  fig-prefix: Figure    # (default is "Figure")
  tbl-prefix: Table     # (default is "Table")
  ref-hyperlink: true   # (default is true)
  title-delim: ":"      # (default is ":")

bibliography: references.bib
csl: csl_file.csl

format:
  html:
    toc: true
    toc-depth: 5
    toc-location: right
    toc-expand: true
    number-sections: true
    number-depth: 5
    smooth-scroll: true
    theme:
      light:
        - flatly
        #- custom.scss
      dark:
        - solar
  docx:
    reference-doc: custom-reference.docx
    toc: true
    toc-depth: 5
    number-sections: true
    number-depth: 5
    prefer-html: true
    highlight-style: github
  pdf:
    pdf-engine: xelatex
    # prefer-html: true  # does not work with html widgets like reactable
    documentclass: scrreprt
    papersize: a4
    toc-depth: 5
    number-sections: true
    number-depth: 5
    keep-tex: false
    include-in-header:
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
        \DefineVerbatimEnvironment{OutputCode}{Verbatim}{breaklines,commandchars=\\\{\}}
    include-before-body:
      text: |
        \begin{flushleft}
        \begin{sloppypar}
        \RecustomVerbatimEnvironment{verbatim}{Verbatim}{
          showspaces = false,
          showtabs = false,
          breaksymbolleft={}, % Need pacakge fvextra
          breaklines
          % Note: setting commandchars=\\\{\} here will cause an error
        }
    include-after-body:
      text: |
        \end{sloppypar}
        \end{flushleft}




